# Generated by Django 3.0.10 on 2025-06-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
